project:
  type: website
  output-dir: docs

website:
  title: "Bayesian algorithms"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      
  sidebar:
    style: "floating"
    search: true
    contents:
        - section: "General methods"
          contents:
            - href: src/RWM.qmd
              text: Random walk Metropolis
            - href: src/RWM_ode.qmd
              text: RWM on ODE 
            - href: src/DE.qmd
              text: DE MCMC
            - href: src/SMC.qmd
              text: SMC
            - href: src/Gibbs.qmd
              text: Gibbs
        - section: "State Space Models"
          contents:
            - href: src/particle_filter.qmd
              text: Particle filter
            - section: Logistic growth
              href: src/logistic_growth.qmd
              contents:
              - href: src/logistic_growth_MCMC_wo_states_v1.qmd
                text: MCMC without states v1
              - href: src/logistic_growth_MCMC_wo_states_v2.qmd
                text: MCMC without states v2
              - href: src/logistic_growth_MCMC_wo_states_v3.qmd
                text: MCMC without states v3
              - href: src/logistic_growth_MCMC.qmd
                text: MCMC
              - href: src/logistic_growth_pMCMC.qmd
                text: pMCMC
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



